version: '3.8'

services:
  self-detailing-frontend:
    image: "${DOCKERHUB_REPO}:${VERSION}"
    container_name: self-detailing-frontend
    restart: always

    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=frontend.self-detailing.duckdns.org
      - LETSENCRYPT_HOST=frontend.self-detailing.duckdns.org
      - LETSENCRYPT_EMAIL=soshinaalena6415@gmail.com
      # - BACKEND_PASSWORD=${BACKEND_PASSWORD}
      # - BACKEND_USERNAME=${BACKEND_USERNAME}

    expose:
      - "18081"

    ports:
      - "18081:80"

    networks:
      - backend-self-detailing-network

networks:
  backend-self-detailing-network:
    external: true
